src/Web/ExpensesManager.Web/Controllers/DashboardController.cs
using ExpensesManager.Application.BusinessRules.Interfaces.Transaction;
using ExpensesManager.Application.Services.LoggedUser;
using ExpensesManager.Domain.Entities;
using ExpensesManager.Web.Filters;
using ExpensesManager.Web.Models;
using ExpensesManager.Web.Utilities.Mapper;
using Microsoft.AspNetCore.Mvc;

namespace ExpensesManager.Web.Controllers
{
    [ServiceFilter(typeof(AuthorizationFilter))]
    public class DashboardController : Controller
    {
        public async Task<IActionResult> Index([FromServices] IGetTransaction getTransaction, [FromServices] ILoggedUser loggedUser)
        {
            DashboardModel dashboardModel = await GetDashboardModel(getTransaction, loggedUser);

            return View(dashboardModel);
        }

        public async Task<ActionResult> LoadCharts([FromServices] IGetTransaction getTransaction, [FromServices] ILoggedUser loggedUser)
        {
            try
            {
                DashboardModel dashboardModel = await GetDashboardModel(getTransaction, loggedUser);

                return new JsonResult(new { success = true, dashboardModel });
            }
            catch (Exception ex)
            {
                return new JsonResult(new { success = false, error = ex.Message });
            }
        }

        private async Task<DashboardModel> GetDashboardModel([FromServices] IGetTransaction getTransaction, [FromServices] ILoggedUser loggedUser)
        {
            User user = await loggedUser.GetLoggedUser();

            List<Transaction> incomeList = await getTransaction.Execute(Domain.Enum.CategoryType.Income, user.Id);

            List<Transaction> expensesList = await getTransaction.Execute(Domain.Enum.CategoryType.Expenses, user.Id);

            DashboardModel dashboardModel = new DashboardMapper().Map(incomeList, expensesList);

            return dashboardModel;
        }
    }
}

src/Web/ExpensesManager.Web/Controllers/LogoutController.cs
using ExpensesManager.Application.Services.Token;
using Microsoft.AspNetCore.Mvc;

namespace ExpensesManager.Web.Controllers
{
    public class LogoutController : Controller
    {
        public ActionResult Logout([FromServices] TokenService tokenService)
        {
            tokenService.DeleteCookie(Response);

            return RedirectToAction("Index", "Login");
        }
    }
}

src/Web/ExpensesManager.Web/Controllers/ManagerController.cs
using ExpensesManager.Application.BusinessRules.Interfaces.Category;
using ExpensesManager.Application.BusinessRules.Interfaces.Transaction;
using ExpensesManager.Application.Services.LoggedUser;
using ExpensesManager.Domain.Entities;
using ExpensesManager.Exceptions.Exceptions;
using ExpensesManager.Exceptions.ResourcesMessage;
using ExpensesManager.Web.Filters;
using ExpensesManager.Web.Models;
using ExpensesManager.Web.Utilities.Mapper;
using Microsoft.AspNetCore.Mvc;

namespace ExpensesManager.Web.Controllers
{
    [ServiceFilter(typeof(AuthorizationFilter))]
    public class ManagerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> AddCategory([FromForm] CategoryModel categoryModel, [FromServices] ICreateCategory createCategory, [FromServices] ILoggedUser loggedUser)
        {
            try
            {
                Category category = new CategoryMapper().Map(categoryModel);

                User user = await loggedUser.GetLoggedUser();

                category.UserId = user.Id;

                await createCategory.Execute(category);

                return new JsonResult(new { success = true, category });
            }
            catch (Exception ex)
            {
                if (ex is ValidationException)
                {
                    ValidationException validationsError = ex as ValidationException;

                    return new JsonResult(new { success = false, error = validationsError.ErrorMessage });
                }

                return new JsonResult(new { success = false, error = ex.Message });
            }
        }

        public async Task<ActionResult> AddTransaction([FromForm] TransactionModel transactionModel, [FromServices] ICreateTransaction createTransaction, [FromServices] ILoggedUser loggedUser)
        {
            try
            {
                Transaction transaction = new TransactionMapper().Map(transactionModel);

                User user = await loggedUser.GetLoggedUser();

                transaction.UserId = user.Id;

                await createTransaction.Execute(transaction);

                return new JsonResult(new { success = true, message = RESPONSEMSG.TRANSACTION_SUCCESS });
            }
            catch (Exception ex)
            {
                if (ex is ValidationException)
                {
                    ValidationException validationsError = ex as ValidationException;

                    return new JsonResult(new { success = false, error = validationsError.ErrorMessage });
                }

                return new JsonResult(new { success = false, error = ex.Message });
            }
        }

        public async Task<ActionResult> LoadCategoriesList([FromServices] IGetCategory getCategory, [FromServices] ILoggedUser loggedUser)
        {
            try
            {
                User user = await loggedUser.GetLoggedUser();

                List<Category> categoryList = await getCategory.Execute(user.Id);

                List<CategoryModel> categoryModelList = new List<CategoryModel>();

                foreach (Category category in categoryList)
                    categoryModelList.Add(new CategoryMapper().Map(category));

                return PartialView("_PartialCategoryList", categoryModelList);
            }
            catch (Exception ex)
            {
                return new JsonResult(new { success = false, error = ex.Message });
            }
        }
    }
}

src/Web/ExpensesManager.Web/Controllers/UserController.cs
using ExpensesManager.Application.BusinessRules.Interfaces.AdditionalInfoUser;
using ExpensesManager.Application.BusinessRules.Interfaces.User;
using ExpensesManager.Application.BusinessRules.Interfaces.UserImage;
using ExpensesManager.Application.Services.Images;
using ExpensesManager.Application.Services.LoggedUser;
using ExpensesManager.Application.Validators;
using ExpensesManager.Domain.Entities;
using ExpensesManager.Exceptions.Exceptions;
using ExpensesManager.Exceptions.ResourcesMessage;
using ExpensesManager.Web.Filters;
using ExpensesManager.Web.Models;
using ExpensesManager.Web.Utilities.Mapper;
using Microsoft.AspNetCore.Mvc;

namespace ExpensesManager.Web.Controllers
{
    [ServiceFilter(typeof(AuthorizationFilter))]
    public class UserController : Controller
    {
        public async Task<IActionResult> Index([FromServices] ILoggedUser loggedUser, [FromServices] IUpdateAdditionalInfoUser updateAdditionalInfoUser, [FromServices] IGetUserImage getUserImage)
        {
            AdditionalInfoUserModel additionalInfoUserModel = await GetAdditionalInfoUserModel(loggedUser, updateAdditionalInfoUser, getUserImage);

            return View(additionalInfoUserModel);
        }

        public async Task<ActionResult> UpdateUserData([FromForm] AdditionalInfoUserModel additionalInfoUserModel, [FromServices] IUpdateUser updateUser, [FromServices] IUpdateAdditionalInfoUser updateAdditionalInfoUser, [FromServices] ICreateAdditionalInfoUser createAdditionalInfoUser)
        {
            try
            {
                await UpdateUser(additionalInfoUserModel, updateUser);

                await UpdateAdditionalInfoUser(additionalInfoUserModel, updateAdditionalInfoUser, createAdditionalInfoUser);

                TempData["SuccessMessage"] = RESPONSEMSG.ADDITIONALINFO_SUCCESS;
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                if (ex is ValidationException)
                {
                    ValidationException validationsError = ex as ValidationException;
                    TempData["ErrorMessage"] = validationsError.ErrorMessage;

                    return RedirectToAction("Index");
                }

                TempData["ErrorMessage"] = VALIDATIONMSG.ADDITIONALINFO_ERROR;
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> UploadUserPicture([FromForm] AdditionalInfoUserModel additionalInfoUserModel, [FromServices] ICreateUserImage createUserImage, [FromServices] IUpdateUserImage updateUserImage, [FromServices] ImageService imageService)
        {
            try
            {
                UserImage existingUserImage = await updateUserImage.Execute(additionalInfoUserModel.UserId.Value);              

                UserImage userImage = imageService.SaveProfileImage(additionalInfoUserModel.ProfileImage, additionalInfoUserModel.UserId.Value);

                if (existingUserImage != null)
                    await updateUserImage.Update(imageService.DeleteProfileImage(existingUserImage));

                await createUserImage.Execute(userImage);

                TempData["SuccessMessage"] = RESPONSEMSG.IMAGE_SUCCESS;
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                if (ex is ValidationException)
                {
                    ValidationException validationsError = ex as ValidationException;
                    TempData["ErrorMessage"] = validationsError.ErrorMessage;

                    return RedirectToAction("Index");
                }

                TempData["ErrorMessage"] = RESPONSEMSG.IMAGE_ERROR;
                return RedirectToAction("Index");
            }
        }

        private static async Task UpdateUser([FromForm] AdditionalInfoUserModel additionalInfoUserModel, [FromServices] IUpdateUser updateUser)
        {
            User user = await updateUser.Execute(additionalInfoUserModel.UserId.Value);

            user = new UserMapper().Map(user, additionalInfoUserModel);

            UserValidator.ValidateToUpdate(user);

            if (additionalInfoUserModel.HasChangeUser)
                await updateUser.Update(user);
        }

        private static async Task UpdateAdditionalInfoUser([FromForm] AdditionalInfoUserModel additionalInfoUserModel, [FromServices] IUpdateAdditionalInfoUser updateAdditionalInfoUser, [FromServices] ICreateAdditionalInfoUser createAdditionalInfoUser)
        {
            AdditionalInfoUser additionalInfoUser = await updateAdditionalInfoUser.Execute(additionalInfoUserModel.UserId.Value);

            if (additionalInfoUser == null)
            {
                additionalInfoUser = new AdditionalInfoUserMapper().Map(additionalInfoUserModel);

                AdditionalInfoUserValidator.Validate(additionalInfoUser);

                await createAdditionalInfoUser.Execute(additionalInfoUser);
            }
            else
            {
                additionalInfoUser = new AdditionalInfoUserMapper().Map(additionalInfoUser, additionalInfoUserModel);

                AdditionalInfoUserValidator.Validate(additionalInfoUser);

                if (additionalInfoUserModel.HasChange)
                    await updateAdditionalInfoUser.Update(additionalInfoUser);
            }
        }

        private static async Task<AdditionalInfoUserModel> GetAdditionalInfoUserModel([FromServices] ILoggedUser loggedUser, [FromServices] IUpdateAdditionalInfoUser updateAdditionalInfoUser, [FromServices] IGetUserImage getUserImage)
        {
            User user = await loggedUser.GetLoggedUser();

            AdditionalInfoUser additionalInfoUser = await updateAdditionalInfoUser.Execute(user.Id);

            UserImage userImage = await getUserImage.Execute(user.Id);

            return new AdditionalInfoUserMapper().Map(additionalInfoUser, userImage, user);
        }
    }
}

src/Web/ExpensesManager.Web/Views/Shared/_ExternalLayout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/global.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpensesManager.Web.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <main role="main" class="h-100">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/global.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Web/ExpensesManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/global.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/menu.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpensesManager.Web.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-5">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="Index">Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav navbar-flex flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="Index">Gerenciar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Estatísticas</a>
                        </li>
                    </ul>
                    <div>
                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" role="button" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                @await Component.InvokeAsync("UserProfileImage")
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end secondary-background" aria-labelledby="userDropdown">
                                <li><a class="dropdown-item mb-2" asp-controller="User" asp-action="Index">Perfil</a></li>
                                <li><a class="dropdown-item" asp-controller="Logout" asp-action="Logout">Sair</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 h-100">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/global.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>