src/Web/ExpensesManager.Web/Controllers/SignUpController.cs
using ExpensesManager.Application.BusinessRules.Interfaces.User;
using ExpensesManager.Application.Validators;
using ExpensesManager.Domain.Entities;
using ExpensesManager.Exceptions.Exceptions;
using ExpensesManager.Exceptions.ResourcesMessage;
using ExpensesManager.Web.Models;
using ExpensesManager.Web.Utilities.Mapper;
using Microsoft.AspNetCore.Mvc;

namespace ExpensesManager.Web.Controllers
{
    public class SignUpController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> AddUser([FromForm] UserModel userModel, [FromServices] ICreateUser createUser, [FromServices] IGetUser getUser)
        {
            try
            {
                User user = new UserMapper().Map(userModel);

                await ValidateUser(user, getUser);

                await createUser.Execute(user);

                return View("/Views/SignUp/ConfirmSignUp.cshtml");
            }
            catch (Exception ex)
            {
                if (ex is ValidationException)
                {
                    ValidationException validationsError = ex as ValidationException;
                    TempData["ErrorMessage"] = validationsError.ErrorMessage;

                    return RedirectToAction("Index");
                }

                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        private async Task ValidateUser(User user, [FromServices] IGetUser getUser)
        {
            User existingUser = await getUser.Execute(user.Mail);

            if (existingUser != null)
                throw new ValidationException(VALIDATIONMSG.EXISTING_USER);

            UserValidator.Validate(user, true);
        }
    }
}

src/Web/ExpensesManager.Web/Views/SignUp/ConfirmSignUp.cshtml
@{
    ViewData["Title"] = "Sucesso";
    Layout = "_ExternalLayout";
}

<div class="text-center row mt-5 mb-4 pt-4 d-flex justify-content-center">
    <i class="bi bi-check-circle display-3 mb-4"></i>
    <h1>Usuário criado com sucesso</h1>
    <p class="mb-0">
        <a href="/Login" class="fw-bold">Login</a>
    </p>
</div>

src/Web/ExpensesManager.Web/Views/SignUp/Index.cshtml
@{
    ViewData["Title"] = "Cadastro";
    Layout = "_ExternalLayout";
}
@using ExpensesManager.Web.Models;
@model UserModel;

<div class="row mt-5 mb-4 pt-4 d-flex justify-content-center">
    @if (TempData["ErrorMessage"] != null)
    {
        <span id="error-message">@TempData["ErrorMessage"]
            <button type="button" class="btn btn-danger btn-sm close-alert position-absolute" style="right: 20px" aria-label="Close">X</button>
        </span>
    }

    <form asp-controller="SignUp" asp-action="AddUser" method="post" class="mt-3 col-lg-4" id="registrationForm">
        <fieldset>
            <h1 class="text-center mb-4">CADASTRO</h1>
            <div class="mb-3">
                <input asp-for="Name" type="text" class="form-control input-font-size" id="nameInput" placeholder="Nome" minlength="3" maxlength="30" required>
            </div>
            <div class="mb-3">
                <input asp-for="Mail" type="email" class="form-control input-font-size" id="identificationInput" placeholder="E-mail" required>
            </div>
            <div class="mb-3">
                <input asp-for="Password" type="password" class="form-control input-font-size" id="passwordInput" placeholder="Senha" required maxlength="30">
            </div>
            <div class="mb-3">
                <input type="password" class="form-control input-font-size" id="confirmPasswordInput" placeholder="Confirmar Senha" required maxlength="30">
                <small id="passwordMatchHelpBlock" class="form-text text-danger d-none">As senhas não coincidem.</small>
            </div>

            <ul id="passwordCriteriaList" class="list-unstyled">
                <li id="lengthCriteria" class="text-danger f-1"><small>Pelo menos 8 caracteres</small></li>
                <li id="uppercaseCriteria" class="text-danger"><small>Pelo menos 1 letra maiúscula</small></li>
                <li id="lowercaseCriteria" class="text-danger"><small>Pelo menos 1 letra minúscula</small></li>
                <li id="numberCriteria" class="text-danger"><small>Pelo menos 1 número</small></li>
                <li id="specialCharCriteria" class="text-danger"><small>Pelo menos 1 caractere especial (@@, $, !, %, *, ?, &, .)</small></li>
            </ul>

            <div>
                <button type="submit" asp-controller="SignUp" asp-action="AddUser" class="button-font-size btn button-primary w-100">Cadastrar</button>
            </div>
        </fieldset>

        <div class="text-center text-lg-start d-flex">
            <p class="small mt-2 pt-1 mb-0">
                Já tem uma conta? <a href="/Login" class="fw-bold">Login</a>
            </p>
        </div>
    </form>
</div>

<script src="~/js/password.js" asp-append-version="true"></script>